### PR TITLE
Replace Rakefile with Makefile.

### PR DESCRIPTION
**Pull request by moll**
What is it with these youngsters these days wrapping shell in Ruby, right!
Obviously I didn't actually try Makefile this as I'm a professional and can't be bothered with operational side of things.

### CODE REVIEW

**Comment by moll** [comment]
Given that you're a young guy, you can run (GNU) Make with `make`. Definitely test how much faster this is than Rake!

**Comment by jarmo** [comment]
Thank you for your effort, my friend, but I'm not going to accept this PR since this `Rakefile` can be deleted altogether, which is an even better solution!

By the way, does it work on a Windows platform or would it introduce yet another dependency to this project?

**Comment by moll** [comment]
Dependency on Make is one you can amortize over all of your projects, be they in C, Ruby, Haskell or JavaScript. Save the time of learning all of their idiosyncratic Make-clones by using the real thing. ;)

**Comment by jarmo** [comment]
So you're saying that everyone will start only using Make in their projects so that you don't have to use all of these yet-another-make's at one point? That would be good, yes!

**Comment by moll** [comment]
Anyone doing anything in more than one language has to. There's no de facto standard Make clone for most of them. And that's a good thing. People are learning not to reinvent unnecessary wheels.

**Pull request closed without merging**
